# Generated by Django 5.0 on 2024-01-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_movie_cover_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='gallery',
        ),
    ]
