# Generated by Django 5.0 on 2024-01-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_image_movie_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='gallery',
        ),
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/cover'),
        ),
    ]
